// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocA-cdNJ7RXEsbzeAQGVpAsy_MReot3A',
    appId: '1:741106847119:web:65d3f6693505fb00f40ffa',
    messagingSenderId: '741106847119',
    projectId: 'anbari-manager',
    authDomain: 'anbari-manager.firebaseapp.com',
    storageBucket: 'anbari-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7tsa9jFw8AwLLJZG5KQm_UeKNTNeBYE',
    appId: '1:741106847119:android:80263537ae68a268f40ffa',
    messagingSenderId: '741106847119',
    projectId: 'anbari-manager',
    storageBucket: 'anbari-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8NAIJd8m1RNZt8zBEMxOJaQqyLDbAn0',
    appId: '1:741106847119:ios:f44ee076ef4737f8f40ffa',
    messagingSenderId: '741106847119',
    projectId: 'anbari-manager',
    storageBucket: 'anbari-manager.firebasestorage.app',
    iosBundleId: 'com.example.roommateChores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDocA-cdNJ7RXEsbzeAQGVpAsy_MReot3A',
    appId: '1:741106847119:web:ae82006f3bc38d92f40ffa',
    messagingSenderId: '741106847119',
    projectId: 'anbari-manager',
    authDomain: 'anbari-manager.firebaseapp.com',
    storageBucket: 'anbari-manager.firebasestorage.app',
  );
}
